const CDN = 'https://delfht6ndmo4c.cloudfront.net/wp-content/uploads/';
const LOGO = `${CDN}2020/07/09163221/logo_tmz.png`;

const pages = {
  '/': { title: 'Engineering digital outcomes that matter.', kicker: 'Technology partner / North America · EMEA · APAC', image: `${CDN}2020/02/Product_Development_banner.jpg`, introTitle: 'A trusted partner for what is next.', intro: 'TekMindz is a trusted partner for delivering technology solutions to startups, business enterprises, and governments across industries in North America, EMEA, and APAC. Our services include Product Engineering, Application Services, Digital and Consulting.', type: 'home' },
  '/company/about-us/': { title: 'About Us', kicker: 'Company / About TekMindz', image: `${CDN}2020/08/about_us_banner.jpg`, heading: 'Who We Are', body: ['TekMindz is a trusted partner for delivering technology solutions to startups, business enterprises, and governments across industries in North America, EMEA, and APAC. Our services include Product Engineering, Application Services, Digital and Consulting.', 'Innovation is the cornerstone of our work approach and we make significant investments in next generation technologies and solutions to help deliver advanced solutions to our clients.', 'Values such as trust, growth mindset, adaptability, integrity, transparency, and excellence form the bedrock of our company.'], section: 'Our Culture', sectionBody: 'We believe in creating an environment that encourages a passion for learning. We want our employees to constantly broaden their horizons. Sustaining innovation and passion even during challenging times are the hallmarks of a growth-oriented mindset.' },
  '/services/product-engineering/': { title: 'Product Engineering', kicker: 'Services / Product Engineering', image: `${CDN}2020/02/Product_Development_banner.jpg`, heading: 'Product Engineering at the Fastest Go-to-Market Speed!', body: ['TekMindz’s full lifecycle product engineering services offer application engineering services for all stages of the software product development lifecycle — from architecting, designing and implementing technology to sustaining technology footprints and supporting associated business functions and processes.', 'We have been enabling start-ups to mid-sized product companies deliver greater value to their customers by helping them enhance and future enable their product offerings and achieve rapid time to market.'], section: 'Product Engineering Offerings', list: ['Product Development', 'Product Sustenance', 'Product Testing', 'Product Deployment', 'Product Support', 'Product Management'] },
  '/services/application/': { title: 'Application Services', kicker: 'Services / Application', image: `${CDN}2020/02/Application_Development_banner.jpg`, heading: 'Application services built for change.', body: ['TekMindz offers full-lifecycle application services encompass development, integration, modernization and independent testing & validation—leveraging AI, Agile, DevOps, APIs, Microservices and more.'], section: 'What We Do', list: ['Application Development', 'Implementation & Rollout', 'Application Support & Maintenance', 'DevOps Services', 'Integration Services'] },
  '/services/digital-transformation/': { title: 'Digital Transformation', kicker: 'Services / Digital', image: `${CDN}2020/02/Digital_Transformation_banner.jpg`, heading: 'Make digital work harder for your business.', body: ['TekMindz has been enabling enterprises to navigate complex legacy landscapes and evolve into Digital businesses with comprehensive Enterprise Digital Transformation strategies.'], section: 'Our Approach', list: ['Digital Strategy', 'Digitization', 'Experience Design', 'Analytics', 'Cloud Enablement'] },
  '/services/consulting/': { title: 'Consulting', kicker: 'Services / Consulting', image: `${CDN}2020/02/Consulting_banner.jpg`, heading: 'Technology decisions with business intent.', body: ['TekMindz brings well over a decade of Consulting experience across traditional legacy and next-gen digital technologies with flexible and scalable engagement and delivery models.'], section: 'Consulting Services', list: ['Agile Consulting', 'IT Consulting', 'Operations Consulting', 'Software Architecture Consulting Services'] },
  '/technologies/': { title: 'Technologies', kicker: 'Technology / What we serve with', image: `${CDN}2020/05/technologies_banner.jpg`, heading: 'Technology We Serve With', body: ['New technologies are consistently disrupting the market causing mayhem in the enterprise IT landscape. TekMindz helps organizations stay consistent in the digital race through open-source software, technologies, open-standards and middleware frameworks.', 'We specialize in creating powerful and intelligent solutions, breakthrough products and enterprise applications using open-source technologies.'], section: 'Our Technology Practice', list: ['Opensource / Standards / Framework / Middleware', 'Frontend Engineering', 'Mobile Development', 'DevOps', 'Testing Automation', 'Analytics', 'Cloud', 'Identity and Access Management Software', 'Caching', 'Blockchain', 'Artificial Intelligence / Machine Learning'] },
  '/industries/healthcare/': { title: 'Healthcare', kicker: 'Industries / Healthcare', image: `${CDN}2020/04/healthcare_banner.jpg`, heading: 'The Advantage you get with TekMindz', body: ['Healthcare industry is going through massive changes due to the evolution of data and digital practices. It is crucial that you collaborate with someone who can not only predict and build platforms but also innovate by integrating data with technology to create state-of-the-art solutions.', 'TekMindz is one of the most popular names for groundbreaking IT and technology solutions in the healthcare domain. Our dedicated team of professionals has the best offering in OpenMRS, DHIS 2, FHIR Standard and more.'], section: 'Learn Why TekMindz for Healthcare', list: ['Opensource Healthcare Frameworks Expertise', 'Innovation in Healthcare Solutions Expertise', 'OpenMRS Expertise', 'DHIS2 Expertise'] },
  '/industries/energy-utility/electric-vehicle/': { title: 'Electric Vehicle', kicker: 'Industries / Energy & Utility', image: `${CDN}2020/04/electric_vehicle_banner.jpg`, heading: 'Powering the next generation of mobility.', body: ['Learn how TekMindz delivers best-in-industry solutions across multi-level Energy & Utility operations, offering solutions to enterprises for Charge Management Systems using OCPP and OpenADR.', 'Our core expertise in key EV areas span across Battery Management Systems, Environment and Regulatory Compliances, Supply Chain, Protocol Implementation, Analytics & Visualization, Network Operations, Asset & Fleet Management and more.'], section: 'EV Expertise', list: ['Charge Station Management System', 'Battery Management Systems', 'Analytics & Visualization', 'Network Operations', 'Asset & Fleet Management'] },
  '/contact-us/': { title: 'Contact Us', kicker: 'Start a conversation', image: `${CDN}2020/05/contact_banner.jpg`, contact: true }
};

const nav = [
  { label: 'Services', href: '/services/', groups: [
    ['Product Engineering', [['New Product Development', '/services/product-engineering/new-product-development/'], ['Product Sustenance', '/services/product-engineering/product-sustenance/'], ['Product Testing', '/services/product-engineering/product-testing/'], ['Product Deployment', '/services/product-engineering/product-deployment/'], ['Product Support', '/services/product-engineering/product-support/'], ['Independent Testing Services', '/services/product-engineering/independent-testing-services/']]],
    ['Application', [['Application Development', '/services/application/application-development/'], ['Application Support & Maintenance', '/services/application/application-support-maintenance/'], ['DevOps Services', '/services/application/devops-services/'], ['Integration Services', '/services/application/integration-services/']]],
    ['Digital', [['Cloud Enablement', '/services/cloud-enablement/'], ['Digital Transformation', '/services/digital-transformation/'], ['Digitization', '/services/digitization/'], ['AI & Machine Learning', '/services/ai-machine-learning/'], ['RPA', '/services/rpa/'], ['IoT', '/services/iot/'], ['Analytics', '/services/analytics/'], ['Experience', '/services/experience/'], ['Mobile', '/services/mobile/']]],
    ['Consulting', [['Agile Consulting', '/services/consulting/agile/'], ['Information Technology Consulting', '/services/consulting/it/'], ['Operation Consulting', '/services/consulting/operation/'], ['Software Architecture Consulting', '/services/consulting/software-architecture-consulting-services/']]]
  ]},
  { label: 'Industries', href: '/industries/', groups: [
    ['Energy & Utility', [['Electric Vehicle', '/industries/energy-utility/electric-vehicle/'], ['Fleet', '/industries/energy-utility/fleet/'], ['Battery Energy Services', '/industries/energy-utility/smart-battery-system/']]],
    ['Healthcare', [['Opensource Healthcare Framework', '/industries/healthcare/open-source-healthcare-framework/'], ['OpenMRS', '/industries/healthcare/openmrs/'], ['DHIS2', '/industries/healthcare/dhis2/'], ['FHIR Standard', '/industries/healthcare/fhir-standard/']]],
    ['eGovernance', [['eGovernance overview', '/industries/egovernance/']]]
  ]},
  { label: 'Technologies', href: '/technologies/' },
  { label: 'Company', href: '/company/', groups: [['Company', [['About Us', '/company/about-us/'], ['Leadership', '/company/leadership/'], ['Quality', '/company/quality/'], ['Career', '/company/career/']]]]},
  { label: 'Insights', href: '/insights/' }
];
const footerGroups = [
  ['Offerings', [['Product Engineering', '/services/product-engineering/'], ['Application', '/services/application/'], ['Digital', '/services/digital-transformation/'], ['Consulting', '/services/consulting/'], ['Cloud Enablement', '/services/cloud-enablement/'], ['AI & Machine Learning', '/services/ai-machine-learning/']]],
  ['Industries', [['Healthcare', '/industries/healthcare/'], ['Electric Vehicle', '/industries/energy-utility/electric-vehicle/'], ['eGovernance', '/industries/egovernance/']]],
  ['Company', [['About Us', '/company/about-us/'], ['Leadership', '/company/leadership/'], ['Quality', '/company/quality/'], ['Career', '/company/career/']]]
];

function prettyPath(path) {
  return path.split('/').filter(Boolean).pop()?.replaceAll('-', ' ').replace(/\b\w/g, c => c.toUpperCase()) || 'TekMindz';
}
function currentPage() {
  const path = window.location.pathname.endsWith('/') ? window.location.pathname : `${window.location.pathname}/`;
  return { path, page: pages[path] || { title: prettyPath(path), kicker: 'TekMindz / Capability', image: `${CDN}2020/05/technologies_banner.jpg`, heading: prettyPath(path), body: ['TekMindz delivers technology solutions that help organizations grow at a fast pace and serve their customers and citizens most efficiently.'], section: 'Explore this capability', list: ['Strategy and consulting', 'Product engineering', 'Application services', 'Digital transformation'] } };
}
function header(path) {
  const renderDropdown = groups => groups.map(([heading, links]) => `<div class="dropdown-group"><strong>${heading}</strong>${links.map(([label, href]) => `<a href="${href}">${label}</a>`).join('')}</div>`).join('');
  const renderNavItem = item => item.groups ? `<div class="nav-dropdown"><div class="nav-dropdown-head"><a class="nav-dropdown-toggle ${path.startsWith(item.href) ? 'active' : ''}" href="${item.href}">${item.label}</a><button class="dropdown-toggle" type="button" aria-label="Open ${item.label} menu" aria-expanded="false" data-dropdown-toggle>⌄</button></div><div class="dropdown-menu">${renderDropdown(item.groups)}</div></div>` : `<a class="${path.startsWith(item.href) ? 'active' : ''}" href="${item.href}">${item.label}</a>`;
  return `<div class="topline"><div class="container"><span>Technology solutions for a changing world</span><span>Talk to us: <a href="mailto:talk@tekmindz.com">talk@tekmindz.com</a></span></div></div><header class="header"><div class="container nav"><a class="brand" href="/" aria-label="TekMindz home"><img class="brand-logo" src="${LOGO}" alt="TekMindz" /></a><button class="menu" aria-label="Open menu">☰</button><nav class="nav-links">${nav.map(renderNavItem).join('')}</nav><a class="nav-cta" href="/contact-us/">Talk to us ↗</a></div></header>`;
}
function footer() {
  return `<footer class="footer"><div class="container footer-grid"><div><a class="brand" href="/" aria-label="TekMindz home"><img class="brand-logo" src="${LOGO}" alt="TekMindz" /></a><p class="footer-copy">Let’s drive trust together through continuous learning empowerment, winning attitude and smart work.</p></div>${footerGroups.map(([heading, links]) => `<div><h3>${heading}</h3><div class="footer-links">${links.map(([label, href]) => `<a href="${href}">${label}</a>`).join('')}</div></div>`).join('')}</div><div class="container footer-bottom"><span>Copyright © 2026, Samin TekMindz India Pvt. Ltd. All rights reserved.</span><span><a href="/privacy-policy/">Privacy Policy</a> · <a href="https://www.linkedin.com/company/samin-tekmindz-india-pvt.-ltd.">LinkedIn</a></span></div></footer>`;
}
function hero(page) { return `<section class="hero"><img class="hero-image" src="${page.image}" alt="${page.title}" /><div class="container reveal"><p class="eyebrow">${page.kicker}</p><h1>${page.title}</h1><p>${page.intro || page.body?.[0] || 'Purpose-built technology solutions for real-world outcomes.'}</p><div class="hero-meta">Explore the work</div></div></section>`; }
function home(page) { return `${hero(page)}<section class="section"><div class="container intro-grid"><div><p class="eyebrow">About TekMindz</p><h2>${page.introTitle}</h2></div><div class="intro-copy"><p>${page.intro}</p><p>In addition to our expertise, we firmly believe in the value of MVPs, Rapid Prototyping and POCs and work alongside our clients to ideate and build next-generation solutions.</p><a class="button" href="/company/about-us/">Discover TekMindz ↗</a></div></div></section><div class="stat-band"><div class="container stats"><div class="stat"><strong>250+</strong><span>Clients</span></div><div class="stat"><strong>300+</strong><span>Projects</span></div><div class="stat"><strong>110+</strong><span>Positive feedbacks</span></div><div class="stat"><strong>80</strong><span>Products</span></div></div></div><section class="section alt"><div class="container"><div class="section-heading"><p class="eyebrow">What We Do</p><h2>Technology that moves the work forward.</h2></div><div class="cards">${[['01','Product Development','Transformative IT solutions for improved digital outcomes.','/services/product-engineering/'],['02','Application Development','Full-lifecycle development, integration, modernization and testing.','/services/application/'],['03','Digital','Navigate legacy landscapes and evolve into digital businesses.','/services/digital-transformation/'],['04','Technology','Deep expertise across mobile, cloud and quality engineering.','/technologies/'],['05','Consulting','Flexible, scalable engagement and delivery models.','/services/consulting/'],['06','Get Started','Ready to initiate your transformation journey?','/contact-us/']].map(([n,t,d,h]) => `<a class="card" href="${h}"><span class="card-number">${n}</span><div><h3>${t}</h3><p>${d}</p></div><span class="card-link">Explore ↗</span></a>`).join('')}</div></div></section><section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Why TekMindz</p><h2>Trust is built into the way we deliver.</h2></div><div class="feature-grid">${[['Value Centricity','Proactively adding value to customer business'],['Execution Excellence','Predictable delivery with Quality'],['Collaborative and Transparent','Collaboration & transparency through deployed tools'],['Agile and Flexible','Dynamic response to customer needs']].map(([t,d],i) => `<div class="feature"><small>0${i+1}</small><h3>${t}</h3><p>${d}</p></div>`).join('')}</div></div></section>`; }
function detail(page) { return `${hero(page)}<main class="page-shell"><div class="container content-layout"><article><p class="breadcrumb">Home / ${page.kicker}</p><h2>${page.heading}</h2>${page.body.map(p => `<p>${p}</p>`).join('')}<h3>${page.section}</h3>${page.list ? `<ul>${page.list.map(item => `<li>${item}</li>`).join('')}</ul>` : `<p>${page.sectionBody}</p>`}<a class="button" href="/contact-us/">Let's start a conversation ↗</a></article><aside class="sidebar"><h3>Explore TekMindz</h3>${footerGroups.flatMap(([,links]) => links).slice(0,7).map(([label,href]) => `<a href="${href}">${label}</a>`).join('')}</aside></div></main>`; }
function contact(page) { return `${hero(page)}<main class="section"><div class="container contact-grid"><div><p class="eyebrow">Send Message</p><h2>Let's start a conversation.</h2><p class="intro-copy">TekMindz’s expertise in Professional Services and Managed IT Services can help your organization navigate a changing landscape and new technologies to create a more efficient, productive and secure business.</p><div class="contact-list"><div class="contact-item"><strong>Career</strong><span>careers@tekmindz.com</span></div><div class="contact-item"><strong>Sales</strong><span>talk@tekmindz.com</span></div><div class="contact-item"><strong>Partnership</strong><span>info@tekmindz.com</span></div><div class="contact-item"><strong>India Operations</strong><span>Samin TekMindz India Pvt. Ltd.<br />Unit No. 2, Second Floor, NPX Tower,<br />Sector 153, Noida – 201310 (U.P.) India<br />Tel: +91 120 4010085</span></div></div></div><form class="form"><label>First Name<input required name="firstName" /></label><label>Last Name<input required name="lastName" /></label><label>Email<input required type="email" name="email" /></label><label>Telephone Number<input name="phone" /></label><label>Message<textarea required name="message"></textarea></label><button class="button" type="submit">Submit ↗</button></form></div></main>`; }

const { path, page } = currentPage();
document.title = `${page.title} | TekMindz`;
document.querySelector('#app').innerHTML = `${header(path)}${page.type === 'home' ? home(page) : page.contact ? contact(page) : detail(page)}${footer()}`;
document.querySelector('.menu')?.addEventListener('click', () => document.querySelector('.nav-links').classList.toggle('open'));
document.querySelectorAll('[data-dropdown-toggle]').forEach(toggle => toggle.addEventListener('click', () => {
  const dropdown = toggle.closest('.nav-dropdown');
  const isOpen = dropdown.classList.toggle('open');
  toggle.setAttribute('aria-expanded', String(isOpen));
}));
document.querySelector('.form')?.addEventListener('submit', event => { event.preventDefault(); event.currentTarget.innerHTML = '<p class="eyebrow">Thank you</p><h3>We will get back to you shortly.</h3><p>Your message has been received by the TekMindz team.</p>'; });
